import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {afterEach,it,expect,vi} from 'vitest';
import {staticFixture} from '@ri/app-kit/testing';
import {exportPackage,validateArtifact} from '@ri/app-kit/build';
import {LocalAppsService} from './service';
import {archiveDigest,listCatalog} from './catalog';
vi.mock('@/lib/service/maintenance',()=>({beginActivity:()=>()=>{}}));
let root:string,service:LocalAppsService;
afterEach(async()=>{await service?.dispose();if(root)await fs.rm(root,{recursive:true,force:true});delete process.env.RI_ROOT;delete process.env.RI_LOCAL_APPS;delete process.env.RI_RUNTIME_REPO;});
it('lists inert catalog metadata and reviews a fresh digest-bound package with no records or grants',async()=>{
  root=await fs.mkdtemp(path.join(os.tmpdir(),'ri-catalog-'));process.env.RI_ROOT=path.join(root,'home');process.env.RI_RUNTIME_REPO=root;process.env.RI_LOCAL_APPS='1';
  const catalog=path.join(root,'release/local-apps/catalog');await fs.mkdir(catalog,{recursive:true});
  const artifact=staticFixture(path.join(root,'source'),'ri-fixture'),archive=path.join(catalog,'ri-fixture.tar.gz');await exportPackage(artifact,archive);
  const entry={formatVersion:1,packageId:'ri-fixture',version:'0.1.0',name:'Fixture',description:'Inert synthetic demo',source:'Fixture host',license:'UNLICENSED',hostApi:1,runtime:'static',target:null,artifactDigest:artifact.digest,archiveDigest:await archiveDigest(archive),capabilities:[],demo:{heading:'Fictional demo',caption:'No code or accounts',columns:['Value'],rows:[['Synthetic']]}};
  const metadata=path.join(catalog,'ri-fixture.json');await fs.writeFile(metadata,JSON.stringify(entry));
  expect(await listCatalog()).toEqual([entry]);expect(await fs.stat(process.env.RI_ROOT).catch(()=>null)).toBeNull();
  service=new LocalAppsService();await service.initialize();const draft=await service.addCatalog('ri-fixture');expect(draft.buildStatus).toBe('validated');
  expect(service.store.read()).toMatchObject({instances:[],grants:[],schedules:[]});
  const again = await Promise.all([service.addCatalog('ri-fixture'), service.addCatalog('ri-fixture')]);
  expect(again.map(item => item.id)).toEqual([draft.id, draft.id]);
  await service.dispose(); service = new LocalAppsService(); await service.initialize();
  expect((await service.addCatalog('ri-fixture')).id).toBe(draft.id);
  expect(service.store.read().drafts).toHaveLength(1);
  await fs.writeFile(metadata,JSON.stringify({...entry,artifactDigest:'a'.repeat(64)}));
  await expect(service.addCatalog('ri-fixture')).rejects.toThrow(/differs/);expect(service.store.read().drafts).toHaveLength(1);
  await fs.appendFile(archive,'changed');await expect(service.addCatalog('ri-fixture')).rejects.toThrow(/changed/);
});
it('stages a catalog update for explicit activation, preserving instance data and rejecting stale review',async()=>{
  root=await fs.mkdtemp(path.join(os.tmpdir(),'ri-catalog-update-'));process.env.RI_ROOT=path.join(root,'home');process.env.RI_RUNTIME_REPO=root;process.env.RI_LOCAL_APPS='1';
  const catalog=path.join(root,'release/local-apps/catalog');await fs.mkdir(catalog,{recursive:true});
  const source=path.join(root,'source'),archive=path.join(catalog,'ri-fixture.tar.gz');
  let artifact=staticFixture(source,'ri-fixture');
  const publish=async()=>{await exportPackage(artifact,archive);await fs.writeFile(path.join(catalog,'ri-fixture.json'),JSON.stringify({formatVersion:1,packageId:'ri-fixture',version:'0.1.0',name:'Fixture',description:'Synthetic',source:'Fixture',license:'UNLICENSED',hostApi:1,runtime:'static',target:null,artifactDigest:artifact.digest,archiveDigest:await archiveDigest(archive),capabilities:[],demo:{heading:'Demo',caption:'Synthetic',columns:['Value'],rows:[['Example']]}}));};
  await publish();service=new LocalAppsService();await service.initialize();
  const first=await service.addCatalog('ri-fixture'),installed=await service.activate(first.id,service.store.read().revision);
  const record=path.join(process.env.RI_ROOT,'apps',installed.id,'data/keep.txt');await fs.mkdir(path.dirname(record),{recursive:true});await fs.writeFile(record,'Existing app record');
  const before=service.instance(installed.id).digest,revision=service.store.read().revision;
  await fs.writeFile(path.join(source,'README.md'),'A reviewed package update');artifact=validateArtifact(source);await publish();
  const draft=await service.updateCatalog(installed.id,revision);
  expect(draft).toMatchObject({sourceInstanceId:installed.id,sourcePackageDigest:before,buildStatus:'validated'});
  expect(service.instance(installed.id).digest).toBe(before);
  expect(await fs.readFile(record,'utf8')).toBe('Existing app record');
  const drafts=service.store.read().drafts.length;
  await expect(service.updateCatalog(installed.id,revision)).rejects.toThrow(/changed|revision/i);
  expect(service.store.read().drafts).toHaveLength(drafts);
  const changed=await service.activate(draft.id,service.store.read().revision);
  expect(changed).toMatchObject({id:installed.id,digest:artifact.digest});
  expect(await fs.readFile(record,'utf8')).toBe('Existing app record');
  await expect(service.updateCatalog(installed.id,service.store.read().revision)).rejects.toThrow(/already/);
});
