import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { afterEach, expect, it, vi } from 'vitest';
import { nodeFixture } from '../../../packages/app-kit/test/helpers';
import { exportPackage, validateArtifact } from '@ri/app-kit/build';
import { LocalAppsService } from './service';
import { createLocalAppSourceAdapter } from './source-adapter';
import { decodeSource } from '@/lib/chat-sources/reference';
vi.mock('@/lib/service/maintenance', () => ({ beginActivity: () => () => {} }));
let root: string, service: LocalAppsService;
afterEach(async () => { await service?.dispose(); if (root) await fs.rm(root, { recursive: true, force: true }); delete process.env.RI_LOCAL_APPS; });
it('mentions a generic tools-only app without starting it, calls through its grant, and never retargets removal', async () => {
  root = await fs.mkdtemp(path.join(os.tmpdir(), 'ri-source-app-')); process.env.RI_ROOT = path.join(root, 'home'); process.env.RI_LOCAL_APPS = '1';
  const chatId = randomUUID();
  service = new LocalAppsService(id => id === chatId ? { status: 'active', workspaceId: null } : null);
  await service.initialize();
  const artifact = await nodeFixture(path.join(root, 'package'));
  delete artifact.manifest.extensions['com.ri'].ui;
  await fs.writeFile(path.join(artifact.packageDir, 'plugin.json'), JSON.stringify(artifact.manifest));
  const headless = validateArtifact(artifact.packageDir), archive = path.join(root, 'fixture.tgz');
  await exportPackage(headless, archive);
  const draft = await service.import(archive), installed = await service.activate(draft.id, service.store.read().revision);
  await service.engine.stop(installed.id);
  const adapter = createLocalAppSourceAdapter(() => service), ctx = { chatId, workspaceId: null, harnessReady: true };
  const validate = vi.spyOn(service, 'artifact');
  const [source] = await adapter.list(ctx);
  expect(source).toMatchObject({ status: 'needs_access', chat: true, view: 'none' }); expect(validate).not.toHaveBeenCalled();
  expect(service.engine.condition(installed.id).condition).not.toBe('running');
  await service.store.edit(undefined, state => { state.grants.push({ id: randomUUID(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), instanceId: installed.id, principal: { kind: 'chat', id: chatId }, actions: ['increment'], riActions: [], connections: [], serviceScopeRef: null, revision: 1, revokedAt: null }); });
  expect((await adapter.list(ctx))[0].status).toBe('ready');
  const ref = decodeSource(source.sourceRef);
  expect((await adapter.actions(ref, ctx)).map(a => a.id)).toEqual(['increment']);
  const open = await service.proposeOpen(installed.id, chatId, '/', {});
  expect(open.view).toBe('summary');
  expect(service.store.read().panels).toEqual([]);
  await adapter.open!(ref, ctx);
  expect(service.store.read().panels).toMatchObject([{ chatId, instanceId: installed.id }]);
  expect(await adapter.call(ref, ctx, 'increment', { amount: 2 }, randomUUID())).toEqual({ value: 2 });
  await expect(service.openView({ id: installed.id, path: '/', query: {} }, 'viewer')).rejects.toMatchObject({ code: 'unsupported' });
  await service.store.edit(undefined, state => { state.instances[0].archived = true; });
  expect((await adapter.list(ctx))[0]).toMatchObject({ sourceRef: source.sourceRef, status: 'unavailable' });
  await expect(adapter.actions(ref, ctx)).rejects.toThrow();
}, 20000);
