import fs from 'node:fs/promises';
import path from 'node:path';
import {afterEach,expect,it} from 'vitest';
import {createTestHome,type TestHome} from '@/test/fixtures/home';
import {newSkill,saveSkill,packageAppSkills,readAppWorkflow,stageAppWorkflow,validateAppWorkflows} from '@/lib/skills/manage';
let home:TestHome;
afterEach(async()=>{await home?.cleanup();});
it('packages managed drafts and supporting resources without creating ambient installs, then stages changes through the manager',async()=>{
  home=await createTestHome();
  const skill=await newSkill({name:'review-records',description:'Review the records selected in the current app. Use for direct and follow-up review requests.',body:'Use the supplied app binding. Ask for missing records. Read references/steps.md. Do not widen grants.'});
  await saveSkill(skill.ref,{files:[{path:'references/steps.md',content:'Read selected records first. Write only when the person asks.'}]});
  const pkg=path.join(home.root,'app-drafts','fixture','package');await fs.mkdir(pkg,{recursive:true});
  const index=await packageAppSkills(pkg,[skill.ref]);
  expect(index).toEqual([{name:'review-records',description:skill.description,file:'skills/review-records/SKILL.md'}]);
  const delivered=await readAppWorkflow(pkg,index,'review-records','references/steps.md');
  expect(delivered.content).toContain('Read selected records first');
  expect(delivered.trust).toContain('Lower-trust');
  await expect(readAppWorkflow(pkg,index,'review-records','../../outside')).rejects.toThrow();
  const staged=await stageAppWorkflow(pkg,index,'review-records');
  expect(staged.location.kind).toBe('draft');
  await saveSkill(staged.ref,{body:'Updated procedure. Use the current app instance.'});
  const rebuilt=await packageAppSkills(pkg,[staged.ref]);
  expect(rebuilt[0].name).toBe('review-records');
  expect((await readAppWorkflow(pkg,rebuilt,'review-records')).content).toContain('Updated procedure');
  expect((await readAppWorkflow(pkg,rebuilt,'review-records','references/steps.md')).content).toContain('Read selected records first');
  await validateAppWorkflows(pkg,rebuilt);
  await expect(validateAppWorkflows(pkg,[{...rebuilt[0],description:'Tampered metadata'}])).rejects.toThrow(/differs/);
  for(const folder of ['skills','.agents/skills','.claude/skills'])await expect(fs.access(path.join(home.root,folder,'review-records'))).rejects.toThrow();
  await saveSkill(staged.ref,{description:''});
  await expect(packageAppSkills(pkg,[staged.ref])).rejects.toThrow();
});
