import { z as rpcZ } from 'zod/v4';
export const createPathSchema = rpcZ.object({ ok: rpcZ.literal(true), path: rpcZ.string() });
export const writeFileSchema = createPathSchema.extend({ size: rpcZ.number() });
export const deletePathSchema = createPathSchema.extend({ kind: rpcZ.enum(['file', 'dir']) });
export const renamePathSchema = rpcZ.object({ ok: rpcZ.literal(true), from: rpcZ.string(), to: rpcZ.string(), kind: rpcZ.enum(['file', 'dir']) });
export const wipApplySchema = rpcZ.union([
  rpcZ.object({ action: rpcZ.literal('copy'), empty: rpcZ.literal(true).optional(), copied: rpcZ.array(rpcZ.string()).optional(), skipped: rpcZ.array(rpcZ.object({ path: rpcZ.string(), reason: rpcZ.string() })).optional() }),
  rpcZ.object({ action: rpcZ.literal('move'), empty: rpcZ.literal(true).optional(), moved: rpcZ.boolean().optional(), conflict: rpcZ.boolean().optional(), stashMessage: rpcZ.string().nullable().optional() }),
]);
// Validate data received across device/service boundaries before exposing it to the UI.

export const fileResponseSchema = rpcZ.object({ "path": rpcZ.string(), "content": rpcZ.union([rpcZ.null(), rpcZ.string()]), "encoding": rpcZ.enum(["utf8", "base64"]), "mime": rpcZ.string(), "size": rpcZ.number().finite(), "isBinary": rpcZ.boolean(), "tooLarge": rpcZ.boolean().optional() }).strip();
export const treeResponseSchema = rpcZ.object({ "entries": rpcZ.array(rpcZ.object({ "path": rpcZ.string(), "name": rpcZ.string(), "kind": rpcZ.enum(["file", "dir"]), "size": rpcZ.number().finite().optional(), "status": rpcZ.enum(["added", "modified", "deleted", "staged", "untracked", "conflict"]).optional(), "mtime": rpcZ.string().optional(), "collapsed": rpcZ.boolean().optional() }).strip()) }).strip();
export const worktreeStatusSchema = rpcZ.object({ "dirty": rpcZ.boolean(), "untracked": rpcZ.array(rpcZ.string()), "modified": rpcZ.array(rpcZ.string()), "staged": rpcZ.array(rpcZ.string()), "ahead": rpcZ.number().finite(), "behind": rpcZ.number().finite(), "sync": rpcZ.object({ "upstream": rpcZ.union([rpcZ.null(), rpcZ.string()]), "upstreamIsBase": rpcZ.boolean(), "base": rpcZ.union([rpcZ.null(), rpcZ.string()]), "behindBase": rpcZ.union([rpcZ.null(), rpcZ.number().finite()]) }).strip().optional() }).strip();
export const diffStatsSchema = rpcZ.object({ "files": rpcZ.number().finite(), "additions": rpcZ.number().finite(), "deletions": rpcZ.number().finite() }).strip();
export const structuredDiffSchema = rpcZ.object({ "files": rpcZ.array(rpcZ.object({ "path": rpcZ.string(), "status": rpcZ.enum(["added", "modified", "deleted", "renamed"]), "oldPath": rpcZ.string().optional(), "hunks": rpcZ.array(rpcZ.object({ "oldStart": rpcZ.number().finite(), "oldLines": rpcZ.number().finite(), "newStart": rpcZ.number().finite(), "newLines": rpcZ.number().finite(), "lines": rpcZ.array(rpcZ.object({ "kind": rpcZ.enum(["add", "del", "ctx"]), "text": rpcZ.string() }).strip()) }).strip()) }).strip()) }).strip();
export const wipDetectionSchema = rpcZ.object({ "modified": rpcZ.array(rpcZ.string()), "untracked": rpcZ.array(rpcZ.string()) }).strip();
export const prResponseSchema = rpcZ.object({ "pr": rpcZ.union([rpcZ.null(), rpcZ.object({ "number": rpcZ.number().finite(), "url": rpcZ.string(), "state": rpcZ.enum(["OPEN", "CLOSED", "MERGED"]), "isDraft": rpcZ.boolean(), "headRefName": rpcZ.string(), "baseRefName": rpcZ.string(), "title": rpcZ.string(), "updatedAt": rpcZ.string(), "mergeable": rpcZ.union([rpcZ.null(), rpcZ.literal("MERGEABLE"), rpcZ.literal("CONFLICTING"), rpcZ.literal("UNKNOWN")]), "checks": rpcZ.union([rpcZ.null(), rpcZ.object({ "state": rpcZ.enum(["passing", "failing", "pending"]), "total": rpcZ.number().finite(), "passed": rpcZ.number().finite(), "failed": rpcZ.number().finite(), "pending": rpcZ.number().finite() }).strip()]), "reviewDecision": rpcZ.union([rpcZ.null(), rpcZ.literal("approved"), rpcZ.literal("changes_requested"), rpcZ.literal("review_required")]), "autoMergeEnabled": rpcZ.boolean(), "outOfDate": rpcZ.boolean().optional() }).strip()]), "unavailable": rpcZ.string().optional(), "ghStatus": rpcZ.enum(["not_installed", "not_authenticated"]).optional() }).strip();
export const mergeResponseSchema = rpcZ.object({ "ok": rpcZ.literal(true), "prNumber": rpcZ.number().finite(), "url": rpcZ.string() }).strip();
export const autoMergeResponseSchema = rpcZ.object({ "ok": rpcZ.literal(true), "enabled": rpcZ.boolean(), "prNumber": rpcZ.number().finite(), "url": rpcZ.string() }).strip();
export const workingStateSchema = rpcZ.object({ "branch": rpcZ.union([rpcZ.null(), rpcZ.string()]), "head": rpcZ.union([rpcZ.null(), rpcZ.string()]), "changed": rpcZ.array(rpcZ.string()), "untracked": rpcZ.array(rpcZ.string()), "localOnly": rpcZ.array(rpcZ.string()), "stagedLocal": rpcZ.array(rpcZ.string()), "problem": rpcZ.union([rpcZ.null(), rpcZ.string()]) }).strip();
export const installedAppsResponseSchema = rpcZ.object({ "platform": rpcZ.enum(["aix", "android", "darwin", "freebsd", "haiku", "linux", "openbsd", "sunos", "win32", "cygwin", "netbsd"]), "apps": rpcZ.array(rpcZ.object({ "target": rpcZ.enum(["finder", "terminal", "iterm", "vscode", "cursor", "antigravity", "zed", "sublime", "webstorm"]), "label": rpcZ.string(), "iconDataUrl": rpcZ.union([rpcZ.null(), rpcZ.string()]) }).strip()) }).strip();
export const openInResultSchema = rpcZ.union([rpcZ.object({ "ok": rpcZ.literal(true) }).strip(), rpcZ.object({ "ok": rpcZ.literal(false), "reason": rpcZ.enum(["not_installed", "unsupported", "failed"]), "message": rpcZ.string().optional() }).strip()]);
export const terminalDescriptorSchema = rpcZ.object({ "id": rpcZ.string(), "ownerId": rpcZ.string(), "cwd": rpcZ.string(), "shell": rpcZ.string(), "cols": rpcZ.number().finite(), "rows": rpcZ.number().finite(), "exited": rpcZ.boolean(), "exitCode": rpcZ.union([rpcZ.null(), rpcZ.number().finite()]), "createdAt": rpcZ.string() }).strip();
