import type { InferSelectModel } from 'drizzle-orm';
import * as s from '@/lib/db/schema';
export type { Attachment, StoredAttachment } from '@/lib/db/schema';
export type FinanceSettingsRecord=InferSelectModel<typeof s.financeSettings>;
export type FinanceAccountRecord=InferSelectModel<typeof s.financeAccounts>;
export type FinanceGrantRecord=InferSelectModel<typeof s.financeGrants>;
export type FinanceTransactionRecord=InferSelectModel<typeof s.financeTransactions>;
export type FinanceOverrideRecord=InferSelectModel<typeof s.financeOverrides>;
export type FinanceRuleRecord=InferSelectModel<typeof s.financeRules>;
export type FinanceEvidenceRecord=InferSelectModel<typeof s.financeEvidence>;
export type FinanceAllocationRecord=InferSelectModel<typeof s.financeAllocations>;
export type FinanceRecurringRecord=InferSelectModel<typeof s.financeRecurring>;
export type FinanceBudgetRecord=InferSelectModel<typeof s.financeBudgets>;
export type FinanceScenarioRecord=InferSelectModel<typeof s.financeScenarios>;
export type FinanceViewRecord=InferSelectModel<typeof s.financeViews>;
export type FinanceRevisionRecord=InferSelectModel<typeof s.financeRevisions>;
export type FinanceFindingRecord=InferSelectModel<typeof s.financeFindings>;
export type FinanceSyncRecord=InferSelectModel<typeof s.financeSync>;
export type FinanceFileDeletionRecord=InferSelectModel<typeof s.financeFileDeletions>;
