import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

// A packaged, network-free MCP Apps resource. Declarative data is rendered with
// DOM text nodes. The opaque iframe origin has no Home or desktop authority.
const script = String.raw`
const channel=new URLSearchParams(location.hash.slice(1));
const frameId=channel.get('frame'),hostOrigin=channel.get('origin');
const standardApp=frameId?null:new FinanceMcpSdk.App({name:'Finances',version:'0.1.0'},{},{autoResize:false});
 let payload=null,sequence=2,filters={},changes={categoryLimits:{},goalContributions:{},obligationAmounts:{}},waiting=new Map(),busy=false,scenarioSequence=0,contextRevision=0,selected=[],dirty=false;
function context(){if(!standardApp||!payload)return;const state={selected,viewRevision:payload.view.revision,...(payload.data.budgetRecord?{budgetRevision:payload.data.budgetRecord.revision}:{}),filters,changes};void standardApp.updateModelContext({content:[{type:'text',text:JSON.stringify({formatVersion:1,revision:++contextRevision,state})}]}).catch(showError);}
function select(type,id){const current=selected.findIndex(ref=>ref.type===type&&ref.id===id);if(current>=0)selected.splice(current,1);else selected=[...selected,{type,id}].slice(-50);context();}
function receive(next){if(!next?.view)return;if(payload&&dirty&&(payload.view.revision!==next.view.revision||payload.data.budgetRecord?.revision!==next.data.budgetRecord?.revision||JSON.stringify(payload.data.transactions)!==JSON.stringify(next.data.transactions))){showError(new Error('Records changed while you have a staged edit. Your edit is retained. Review it or discard it before refreshing.'));return;}const first=!payload;payload=next;if(first){changes=payload.scenarioChanges||changes;filters=payload.view.scope.filters||filters;}render();}
function send(method,params){const id=sequence++;parent.postMessage({jsonrpc:'2.0',id,method,params,_meta:{frameId}},hostOrigin);return new Promise((resolve,reject)=>waiting.set(id,{resolve,reject}));}
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=String(text);if(cls)node.className=cls;return node;}
function money(n,currency){return n===null||n===undefined?'Unknown':new Intl.NumberFormat('en-US',{style:'currency',currency:currency||payload.data.currency}).format(n/Math.pow(10,new Intl.NumberFormat('en-US',{style:'currency',currency:currency||payload.data.currency}).resolvedOptions().maximumFractionDigits));}
function tool(name,args){const input={...args,viewRevision:payload.view.revision,viewId:payload.view.id,budgetRevision:payload.data.budgetRecord?.revision,mutationKey:crypto.randomUUID()};return (standardApp?standardApp.callServerTool({name,arguments:input}):send('tools/call',{name,arguments:input})).then(result=>{if(result.isError)throw new Error(result.content?.find(c=>c.type==='text')?.text||'Finance operation failed');return result;});}
function inspect(result){if(!result.inspection)return;const d=el('dialog'),title=el('h2','Protected source record');d.append(title);const pre=el('pre',JSON.stringify(result.inspection.record,null,2));pre.style.whiteSpace='pre-wrap';pre.style.overflowWrap='anywhere';d.append(pre,button('Close',()=>{d.close();d.remove();}));d.style.maxWidth='min(90vw,700px)';d.style.background='#19201b';d.style.color='#e8eee8';d.style.border='1px solid #52664d';document.body.append(d);d.showModal();}

function button(text,action){const b=el('button',text);b.type='button';b.addEventListener('click',action);return b;}
function rows(name,categories){const d=payload.data,all=name==='budget'?d.budget?.categories||[]:d[name]||[];return categories?all.filter(r=>categories.includes(r.category||r.id)):all;}
function heading(c){return el('h2',c.title);}
function render(){
 if(!payload)return;const focus=document.activeElement?.id;const root=document.getElementById('root');root.replaceChildren();
 root.append(el('h1',payload.view.definition.title));root.append(el('p','Server-calculated results • As of '+new Date(payload.data.asOf).toLocaleString(),'muted'));
 if(payload.savedScenarioStale)root.append(el('p','The saved scenario uses an older budget revision. Review it before applying.','notice'));
 if(payload.data.incomplete){const warning=el('p','Some sources are stale or incomplete. These results may be partial.','notice');warning.setAttribute('role','status');root.append(warning);}
 if(payload.data.budget?.cash.reasons.length)root.append(el('p',payload.data.budget.cash.reasons.join('. '),'notice'));
 const grid=el('div',undefined,payload.view.definition.layout==='grid'?'grid':'stack');root.append(grid);
 for(const c of payload.view.definition.components){const card=el('section',undefined,'card');card.append(heading(c));grid.append(card);
  if(c.type==='metric'){const b=payload.data.budget,category=c.categoryId?b?.categories.find(row=>row.id===c.categoryId):b;const key={posted:'postedMinor',pending:'pendingMinor',remaining:'remainingMinor',forecast:'forecastMinor',unallocated:'unallocatedMinor'}[c.metric];const value=c.metric==='cashAvailable'?b?.cash.estimatedMinor:category?.[key];card.append(el('p',money(value),'number'));if(b)card.append(el('p','Budget period '+b.startOn+' to '+b.endOn,'muted'));if(c.metric==='cashAvailable')card.append(el('p',b?.cash.status==='complete'?'Estimated cash available':'Partial estimate. Review assumptions.','muted'));const details=el('details');details.append(el('summary','Inspect sources and calculation'));details.append(el('p',b?.forecastMethod||'No adopted budget','muted'));if(b&&c.metric==='cashAvailable'){for(const account of payload.data.accounts.filter(a=>a.kind!=='mailbox'))details.append(el('p',account.name+' • '+money(account.balanceMinor,account.currency)+' • As of '+(account.asOf||'Unknown'),'source'));details.append(el('p','Card commitments '+money(b.cash.cardCommitmentsMinor)+' • Expected remaining income '+money(b.cash.expectedIncomeMinor),'source'));for(const reserve of b.cash.reserveCommitments||[])details.append(el('p','Reserve '+reserve.id+' • Earmarked '+money(reserve.earmarkedMinor)+' • Already funding known bills '+money(reserve.overlapMinor),'source'));for(const obligation of b.upcoming)details.append(el('p',obligation.dueOn+' • '+obligation.kind.replace('_',' ')+' • '+money(obligation.amountMinor),'source'));}if(category?.limitMinor!==undefined)details.append(el('p','Allocation '+money(category.limitMinor)+' + rollover '+money(category.rolloverMinor)+' − net posted '+money(category.postedMinor),'source'));for(const row of (payload.data.budgetTransactions||[]).filter(t=>(!c.categoryId||t.category===c.categoryId)&&!['income','transfer','card_payment'].includes(t.kind)).slice(0,100)){details.append(el('p',row.postedOn+' • '+row.merchant+' • '+money(row.amountMinor,row.currency)+' • '+row.state,'source'));}card.append(details);}
  if(c.type==='table'){const records=rows(c.dataset,c.categoryIds);if(!records.length){card.append(el('p','No records in this scope. Check account coverage and dates.','muted'));continue;}const scroll=el('div',undefined,'scroll'),table=el('table'),thead=el('thead'),header=el('tr');table.setAttribute('aria-label',c.title);if(['transactions','evidence','findings'].includes(c.dataset))header.append(el('th','Selection'));for(const column of c.columns)header.append(el('th',column.replace(/Minor$/,'').replace(/([A-Z])/g,' $1')));thead.append(header);table.append(thead);const body=el('tbody');for(const r of records.slice(0,250)){const tr=el('tr');if(r.id&&['transactions','evidence','findings'].includes(c.dataset)){const cell=el('td'),pick=el('input');pick.type='checkbox';const type={transactions:'transaction',evidence:'evidence',findings:'finding'}[c.dataset];pick.checked=selected.some(ref=>ref.type===type&&ref.id===r.id);pick.setAttribute('aria-label','Select '+(r.merchant||r.title||r.id));pick.onchange=()=>select(type,r.id);cell.append(pick);tr.append(cell);}for(const column of c.columns){const value=r[column];const cell=el('td',column.endsWith('Minor')?money(value,r.currency):value??'Unknown');if(column===c.columns[0]&&r.id){cell.replaceChildren(button(value??'Inspect record',()=>tool('finance_inspect',{dataset:c.dataset,id:r.id}).then(r=>inspect(r.structuredContent)).catch(showError)));}tr.append(cell);}body.append(tr);}table.append(body);scroll.append(table);card.append(scroll);if(records.length>250)card.append(el('p','Showing the first 250 rows. Narrow the date or account filters.','muted'));}
  if(c.type==='chart'){const records=rows(c.dataset,c.categoryIds);if(!records.length){card.append(el('p','No chart data in this scope.','muted'));continue;}if(new Set(records.map(r=>r.currency).filter(Boolean)).size>1){card.append(el('p','Currencies are shown separately. No conversion rate is assumed.','notice'));for(const r of records)card.append(el('p',r.name+' • '+r.category+' • '+money(r.amountMinor,r.currency),'source'));continue;}if(c.style==='line'&&c.dataset==='trends'){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 640 220');svg.setAttribute('role','img');svg.setAttribute('aria-label',c.title);svg.style.width='100%';const title=document.createElementNS(ns,'title');title.textContent=c.title;svg.append(title);const groups=new Map();for(const row of records){const key=row.category+' • '+row.currency;groups.set(key,[...groups.get(key)||[],row]);}card.append(svg);const lower=Math.min(0,...records.map(r=>r.amountMinor)),upper=Math.max(1,...records.map(r=>r.amountMinor));let color=0;const palette=['#90b37c','#cbbd89','#8bb9c8','#bf98bb'];for(const [name,series] of groups){series.sort((a,b)=>a.name.localeCompare(b.name));const min=lower,max=upper;const path=document.createElementNS(ns,'polyline');path.setAttribute('points',series.map((r,i)=>(24+i*590/Math.max(1,series.length-1))+','+(195-(r.amountMinor-min)*170/Math.max(1,max-min))).join(' '));path.setAttribute('fill','none');path.setAttribute('stroke',palette[color++%palette.length]);path.setAttribute('stroke-width','3');svg.append(path);card.append(el('p',name+' • '+series.map(r=>r.name+': '+money(r.amountMinor,r.currency)).join(' • '),'muted'));}continue;}const amounts=records.flatMap(r=>[Math.abs(r.amountMinor||0),Math.abs(r.limitMinor||0),Math.abs(r.postedMinor||0),Math.abs(r.baselineMinor||0),Math.abs(r.scenarioMinor||0)]),max=Math.max(1,...amounts);for(const r of records.slice(0,100)){const line=el('div',undefined,'chartrow');line.append(el('strong',r.name+(r.category?' • '+r.category:'')));const values=c.dataset==='budget'?[['Plan',r.limitMinor],['Posted',r.postedMinor],['Pending',r.pendingMinor]]:c.dataset==='comparison'?[['Current plan',r.baselineMinor],['Scenario',r.scenarioMinor]]:[['Net spending',r.amountMinor]];for(const [label,value] of values){const labelEl=el('div',label+' '+money(value,r.currency),'muted'),bar=el('div',undefined,'bar');bar.style.width=Math.max(0,Math.min(100,Math.abs(value||0)/max*100))+'%';labelEl.append(bar);line.append(labelEl);}card.append(line);}}
  if(c.type==='timeline'){for(const r of rows(c.dataset).slice(0,100)){const item=el('article',undefined,'timeline');if(r.id&&c.dataset==='evidence'){const pick=el('input');pick.type='checkbox';pick.checked=selected.some(ref=>ref.type==='evidence'&&ref.id===r.id);pick.setAttribute('aria-label','Select '+(r.sourceId||r.id));pick.onchange=()=>select('evidence',r.id);item.append(pick);}item.append(el('strong',r.merchant||r.data?.merchant||r.message||'Evidence'));item.append(el('p',r.occurredOn||r.postedOn||r.data?.occurredOn||'Date unknown','muted'));if(c.dataset==='refunds'){item.append(el('p','Purchase allocation '+money(r.purchaseMinor,r.currency)+' • Promise '+money(r.promiseMinor,r.currency)));item.append(el('p','Unexplained deduction '+money(r.unexplainedDeductionMinor,r.currency)+' • Settlement gap '+money(r.settlementGapMinor,r.currency)));item.append(el('p','Destination: '+r.destination+' • '+r.status,'muted'));for(const part of r.destinationGaps||[])item.append(el('p',part.destination+(part.maskedHint?' ending '+part.maskedHint:'')+' promise '+money(part.promiseMinor,r.currency)+' • Settled '+money(part.settledMinor,r.currency)+' • Gap '+money(part.gapMinor,r.currency),'source'));for(const part of r.nonCashPromises||[])item.append(el('p',part.destination.replace('_',' ')+' promise '+money(part.amountMinor,r.currency)+'. This is not spendable cash.','source'));}else {item.append(el('p',r.data?.excerpt||r.merchant||'Inspect source evidence'));for(const event of r.data?.events||[])item.append(el('p',event.on+' • '+event.kind.replaceAll('_',' ')+' • '+event.source,'source'));}if(r.id)item.append(button('Inspect evidence',()=>tool('finance_inspect',{dataset:c.dataset,id:r.id}).then(r=>inspect(r.structuredContent)).catch(showError)));card.append(item);}if(!rows(c.dataset).length)card.append(el('p','No timeline records.','muted'));}
  if(c.type==='scenario'){const plan=payload.data.budgetRecord?.plan,parameter=c.parameter||'category',field={category:'categoryLimits',income:'incomeMinor',goal:'goalContributions',obligation:'obligationAmounts'}[parameter],category=parameter==='income'?{limitMinor:plan?.incomeMinor}:parameter==='goal'?plan?.goals.find(row=>row.id===c.categoryId):parameter==='obligation'?plan?.obligations.find(row=>row.id===c.categoryId):plan?.categories.find(row=>row.id===c.categoryId);if(!category){card.append(el('p','Category unavailable.','muted'));continue;}const input=el('input');input.type='range';input.min=c.minMinor;input.max=c.maxMinor;input.step=c.stepMinor;input.value=(parameter==='income'?changes.incomeMinor:changes[field]?.[c.categoryId])??category.limitMinor??category.contributionMinor??category.amountMinor;input.id=c.id;input.setAttribute('aria-label',c.title);const output=el('output',money(Number(input.value)));output.htmlFor=input.id;let timer;input.addEventListener('input',()=>{dirty=true;if(parameter==='income')changes.incomeMinor=Number(input.value);else changes[field][c.categoryId]=Number(input.value);output.textContent=money(Number(input.value));clearTimeout(timer);const request=++scenarioSequence;timer=setTimeout(()=>tool('finance_scenario_preview',{changes}).then(result=>{if(request!==scenarioSequence)return;payload=result.structuredContent;render();}).catch(showError),120);});card.append(input,output,el('p','Scenario only. Applying a budget change does not cancel a subscription.','muted'));}
  if(c.type==='filter'){const group=el('div');if(c.dimension==='dates'){for(const key of ['startOn','endOn']){const label=el('label',key==='startOn'?'From':'Until'),input=el('input');input.type='date';input.value=filters[key]||payload.view.scope.filters?.[key]||payload.view.scope[key];input.setAttribute('aria-label',c.title+' '+key);input.addEventListener('change',()=>{dirty=true;filters[key]=input.value;context();});label.append(input);group.append(label);}}else{for(const account of payload.filterAccounts||payload.data.accounts){const label=el('label',account.name),input=el('input');input.type='checkbox';input.checked=(filters.accountIds||payload.view.scope.filters?.accountIds||payload.view.scope.accountIds).includes(account.id);input.addEventListener('change',()=>{const ids=new Set(filters.accountIds||payload.view.scope.filters?.accountIds||payload.view.scope.accountIds);input.checked?ids.add(account.id):ids.delete(account.id);dirty=true;filters.accountIds=[...ids];context();});label.prepend(input);group.append(label);}}group.append(button('Update view filter',()=>tool('finance_filter',{filters,changes}).then(result=>{payload=result.structuredContent;render();}).catch(showError)));card.append(group);}
  if(c.type==='action'){const actions={refresh:'finance_refresh',apply_scenario:'finance_view_apply_scenario',undo_budget:'finance_view_undo_budget',save_scenario:'finance_save_view_scenario',save_filters:'finance_save_view_filters'};const b=button(c.title,async()=>{if(busy)return;busy=true;b.disabled=true;try{const result=await tool(actions[c.action],{changes,filters});payload=result.structuredContent;if(['apply_scenario','undo_budget','save_scenario','save_filters'].includes(c.action))dirty=false;if(!['refresh','save_scenario','save_filters'].includes(c.action))changes={categoryLimits:{},goalContributions:{},obligationAmounts:{}};render();}catch(error){showError(error);}finally{busy=false;b.disabled=false;}});card.append(b);}
 }
 const footer=el('p','Views use live permissions. Refreshing or reopening never repeats a saved mutation.','muted');root.append(footer);if(dirty)root.append(button('Discard staged changes and refresh',async()=>{dirty=false;changes={categoryLimits:{},goalContributions:{},obligationAmounts:{}};filters={};const result=await tool('finance_refresh',{});receive(result.structuredContent);}));if(focus)document.getElementById(focus)?.focus();
 context();reportSize();
}
function reportSize(){if(standardApp){void standardApp.sendSizeChanged({height:Math.max(500,Math.ceil(document.body.getBoundingClientRect().height))});return;}parent.postMessage({jsonrpc:'2.0',method:'ui/notifications/size-changed',params:{height:Math.max(500,Math.ceil(document.body.getBoundingClientRect().height))},_meta:{frameId}},hostOrigin);}
new ResizeObserver(reportSize).observe(document.body);
function showError(error){const node=document.getElementById('error');node.textContent=error?.message||'This action could not finish. Your last valid view remains available.';node.hidden=false;}
if(frameId)addEventListener('message',event=>{if(event.source!==parent||event.origin!==hostOrigin||event.data?._meta?.frameId!==frameId)return;const message=event.data;
 if(message.id&&waiting.has(message.id)){const pending=waiting.get(message.id);waiting.delete(message.id);if(message.error)pending.reject(new Error(message.error.message));else pending.resolve(message.result);}
 if(message.method==='ui/notifications/tool-result'){if(!payload&&message.params.structuredContent.view.scope.filters)filters=message.params.structuredContent.view.scope.filters;payload=message.params.structuredContent;if(payload.scenarioChanges)changes=payload.scenarioChanges;render();}
});
if(standardApp){standardApp.onhostcontextchanged=context=>{document.documentElement.dataset.theme=context.theme||'light';};standardApp.ontoolresult=params=>receive(params.structuredContent);standardApp.connect().then(()=>{document.documentElement.dataset.theme=standardApp.getHostContext()?.theme||'light';}).catch(showError);}else{
send('ui/initialize',{appInfo:{name:'Finances',version:'1.0.0'},protocolVersion:'2026-01-26',appCapabilities:{}}).then(()=>{parent.postMessage({jsonrpc:'2.0',method:'ui/notifications/initialized',_meta:{frameId}},hostOrigin);}).catch(showError);
}
`;
function rendererScript(){const bundle=fs.readFileSync(path.join(process.cwd(),'public/renderer-sdk.js'),'utf8');if(bundle.length>2*1024*1024)throw new Error('Packaged renderer exceeds its limit');return (bundle+'\n'+script).replaceAll('</script','<\\/script');}
export function financeRendererHtml() {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Finances view</title><style>
:root{color-scheme:dark;font:14px system-ui;background:#121713;color:#e8eee8}*{box-sizing:border-box}body{margin:0;padding:24px}h1{font-size:24px;margin:0 0 8px}h2{font-size:14px;margin:0 0 16px;font-weight:600}.muted{color:#a1afa5;font-size:12px;line-height:1.6}.notice{background:#333122;color:#e4d49a;padding:12px;border-radius:8px;font-size:12px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin:24px 0}.stack{display:grid;gap:16px;margin:24px 0}.card{background:#19201b;border:1px solid #303c32;border-radius:12px;padding:20px;min-width:0}.card:has(table),.card:has(.chartrow){grid-column:1/-1}.number{font-size:30px;font-variant-numeric:tabular-nums;margin:8px 0 18px;color:#c4e0bc}button{border:1px solid #52664d;border-radius:7px;background:#263322;color:#e5f0df;padding:8px 12px;cursor:pointer;font:inherit}button:hover{background:#35482e}button:disabled{opacity:.5}button:focus-visible,summary:focus-visible,input:focus-visible{outline:2px solid #b6d69e;outline-offset:3px}.scroll{overflow-x:auto}table{border-collapse:collapse;width:100%;text-align:left;font-size:12px}th{color:#a1afa5;text-transform:capitalize;font-weight:500}th,td{padding:10px 12px;border-bottom:1px solid #303c32;white-space:nowrap}td button{background:none;border:0;padding:0;text-align:left;text-decoration:underline;text-underline-offset:3px}.chartrow{margin:16px 0}.bar{height:8px;background:#90b37c;border-radius:3px;margin:5px 0 10px}.timeline{border-left:2px solid #789269;margin:12px 0;padding:4px 0 12px 16px}input[type=range]{width:100%;accent-color:#b6d69e}output{display:block;font-size:22px;margin:10px 0}summary{cursor:pointer;color:#b8cdb0;font-size:12px}.source{font-size:12px;color:#a1afa5}#error{padding:12px;background:#4c2525;color:#ffd4d4;border-radius:8px} html[data-theme=light]{color-scheme:light;background:#fafbf8;color:#243329}html[data-theme=light] .card,html[data-theme=light] dialog{background:white;border-color:#d8ded8;color:#243329}html[data-theme=light] .muted,html[data-theme=light] .source,html[data-theme=light] th{color:#566c5b}html[data-theme=light] button{background:#edf3e9;color:#243329}html[data-theme=light] .number{color:#35612a} @media(max-width:600px){body{padding:14px}.grid{grid-template-columns:1fr}.card{padding:16px}.number{font-size:26px}}
</style></head><body><p id="error" hidden role="alert"></p><main id="root"><p role="status">Loading your finance view...</p></main><script>${rendererScript()}</script></body></html>`;
}
export function financeRendererPolicy() {
  return `sandbox allow-scripts; default-src 'none'; script-src 'sha256-${createHash('sha256').update(rendererScript()).digest('base64')}'; style-src 'unsafe-inline'; connect-src 'none'; img-src data:; object-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'self'`;
}
