import fs from "node:fs";
import path from "node:path";
export function financeHomeHtml() {
  const sdk = fs.readFileSync(
    path.join(process.cwd(), "public/renderer-sdk.js"),
    "utf8",
  );
  const script = String.raw`
const app=new FinanceMcpSdk.App({name:'Finance',version:'0.1.0'},{},{autoResize:false});let data=null,revision=0;const staged=new Map();
function el(tag,text){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;return node;}
function field(label,value='',type='text',key=label){const wrap=el('label',label),input=el('input');input.value=staged.get(key)??value;input.type=type;input.addEventListener('input',()=>staged.set(key,input.value));wrap.append(input);return [wrap,input];}
function button(label,callback){const node=el('button',label);node.onclick=()=>Promise.resolve(callback()).catch(error=>{document.getElementById('error').textContent=error.message});return node;}
async function call(name,input={}){const result=await app.callServerTool({name,arguments:input});if(result.isError)throw new Error(result.content?.find(c=>c.type==='text')?.text||'Finance operation failed');return result.structuredContent;}
async function refresh(){data=await call('finance_home');render();}
function render(){const root=document.getElementById('root');root.replaceChildren();if(data.accessSetup){root.append(el('h1','Choose account access'),el('p','Choose the records and permissions for this caller.'));const accounts=new Set(JSON.parse(staged.get('accessAccounts')??'[]')),operations=new Set(JSON.parse(staged.get('accessOperations')??'["read"]'));const accept=button('Use selected accounts',()=>call('finance_create_scope',{actorId:data.accessSetup.actorId,accountIds:[...accounts],operations:[...operations]}));const update=()=>{staged.set('accessAccounts',JSON.stringify([...accounts]));staged.set('accessOperations',JSON.stringify([...operations]));accept.disabled=!accounts.size||!operations.size;};for(const account of data.accounts){const label=el('label',account.name),input=el('input');input.type='checkbox';input.checked=accounts.has(account.id);input.onchange=()=>{input.checked?accounts.add(account.id):accounts.delete(account.id);update();};label.prepend(input);root.append(label);}for(const [operation,name] of [['read','Read records'],['evidence','View evidence'],['write','Change records'],['sync','Sync sources']]){const label=el('label',name),input=el('input');input.type='checkbox';input.checked=operations.has(operation);input.onchange=()=>{input.checked?operations.add(operation):operations.delete(operation);update();};label.prepend(input);root.append(label);}update();root.append(accept);return;}if(data.inspection){const {type,record}=data.inspection;root.append(el('h1','Finance record'),el('h2',record.merchant||record.title||record.sourceId||type),el('pre',JSON.stringify(record,null,2)),button('Finance home',()=>app.openLink({url:'/'})));void app.updateModelContext({content:[{type:'text',text:JSON.stringify({formatVersion:1,revision:++revision,state:{selected:[{type,id:record.id}]}})}]});return;}if(staged.size)document.getElementById('notice').textContent='Your unsaved input is retained while records refresh. Review it before applying.';root.append(el('h1','Finances'),el('p','Your accounts, records and saved views. Manual records work without a connector.'));
 if(data.owner&&!data.settings?.enabled)root.append(button('Enable finances',async()=>{await call('finance_setup',{enabled:true,currency:'USD',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,restoreReviewed:true});await refresh();}));
 if(data.settings?.enabled&&data.owner){const section=el('section');section.append(el('h2','Add a manual account'));const [nameWrap,name]=field('Name'),[balanceWrap,balance]=field('Balance in minor units','0','number');section.append(nameWrap,balanceWrap,button('Create account',async()=>{await call('finance_create_account',{name:name.value,kind:'cash',provider:'manual',currency:data.settings.currency,connectionId:null,sourceId:'manual:'+crypto.randomUUID(),balanceMinor:Number(balance.value),balanceIncludesPending:false,historyStart:null,asOf:new Date().toISOString()});staged.delete('Name');staged.delete('Balance in minor units');await refresh();}));root.append(section);}
 if(data.owner&&data.settings?.enabled){const sources=el('section');sources.append(el('h2','Connect account access'),el('p','Manual records are available now. Mailbox reads may cover your mailbox. A receipt query only filters relevance. Bank setup is unavailable unless the host advertises every required operation.'),button('Manage access in Ri',()=>app.openLink({url:'/__host/manage-access'})),button('Show permitted connections',async()=>{const available=await call('finance_source_connections');sources.append(el('p',available.unavailable||!available.connections.length?'No qualified connector access is available. Select an account and grant the declared reads in Ri app settings.':'Select a permitted mailbox below.'));for(const connection of available.connections.filter(item=>item.status==='active'&&available.operations.includes(item.provider==='google'?'gmail.messages.read':'outlook.messages.read'))){const [startWrap,start]=field('Read since','2026-01-01','date','start:'+connection.id),[queryWrap,query]=field('Receipt relevance query','receipt OR invoice OR order OR refund','query:'+connection.id);const consent=el('label','I allow broad mailbox reads for Finance'),acknowledged=el('input');acknowledged.type='checkbox';consent.prepend(acknowledged);sources.append(el('h3',connection.label),startWrap,queryWrap,consent,button('Connect receipt mailbox',async()=>{if(!acknowledged.checked)throw new Error('Confirm mailbox read consent first');await call('finance_connect_mailbox',{connectionId:connection.id,provider:connection.provider,initialStartOn:start.value,query:query.value,monitoring:true,acknowledgeBroadMailboxRead:true});await refresh();}));}}));root.append(sources);}
 root.append(el('h2','Accounts'));for(const account of data.accounts){const section=el('section');section.append(el('h3',account.name),el('p',account.currency+' '+String(account.balanceMinor??'Unknown')+' minor units'));if(data.owner&&account.provider!=='manual'&&account.access==='connected')section.append(button('Disconnect and retain records',async()=>{const result=await call('finance_disconnect_source',{id:account.id,retain:true});document.getElementById('notice').textContent=result.revocationMessage;await refresh();}));
 if(data.owner&&account.provider==='manual'){const area=el('textarea');area.placeholder='date,merchant,amount,category\n2026-10-01,Sample Shop,24.00,shopping';area.setAttribute('aria-label','CSV records');area.value=staged.get('csv:'+account.id)??'';area.addEventListener('input',()=>staged.set('csv:'+account.id,area.value));section.append(button('Choose CSV file',async()=>{const selected=(await call('ri_select_file')).file;if(!selected)return;const bytes=Uint8Array.from(atob(selected.base64),character=>character.charCodeAt(0));area.value=new TextDecoder('utf-8',{fatal:true}).decode(bytes);staged.set('csv:'+account.id,area.value);}),area,button('Import CSV records',async()=>{const result=await call('finance_import_csv',{accountId:account.id,text:area.value,positiveMeansSpending:true});area.value='';staged.delete('csv:'+account.id);document.getElementById('notice').textContent='Imported '+result.imported+' records';await refresh();}));}
 section.append(button('Download account records',async()=>{const rows=await call('finance_transactions',{accountIds:[account.id],startOn:'2000-01-01',endOn:new Date(Date.now()+86400000).toISOString().slice(0,10)});const result=await app.downloadFile({contents:[{type:'resource',resource:{uri:'file:///finance-records.json',mimeType:'application/json',text:JSON.stringify(rows,null,2)}}]});if(result.isError)throw new Error('Download cancelled');}));section.append(button('Save activity view',async()=>{const start=new Date();start.setUTCFullYear(start.getUTCFullYear()-1);await call('finance_create_default_view',{name:'Activity',accountIds:[account.id],startOn:start.toISOString().slice(0,10),endOn:new Date(Date.now()+86400000).toISOString().slice(0,10),budgetId:null,mutationKey:crypto.randomUUID()});await refresh();}));root.append(section);}
 root.append(el('h2','Budgets'));for(const budget of data.budgets){const section=el('section');section.append(el('h3',budget.name),el('p',budget.state));if(data.owner&&budget.state==='proposal')section.append(button('Adopt budget proposal',async()=>{await call('finance_change_budget',{id:budget.id,expectedRevision:budget.revision,mutationKey:crypto.randomUUID(),adopt:true});await refresh();}));const saved=data.views.find(view=>view.scope.budgetId===budget.id&&view.definition.title==='Your monthly budget');section.append(button(saved?'Open budget view':'Save budget view',async()=>{if(saved){await app.openLink({url:'/views/'+saved.id});return;}await call('finance_create_default_view',{name:'Budget',accountIds:budget.accountIds,startOn:budget.plan.startOn,endOn:budget.plan.endOn,budgetId:budget.id,mutationKey:crypto.randomUUID()});await refresh();}));root.append(section);}if(data.owner&&data.accounts.length){const [incomeWrap,income]=field('Monthly income in minor units','0','number');root.append(incomeWrap,button('Create budget proposal',async()=>{await call('finance_propose_budget',{accountIds:data.accounts.filter(account=>account.kind!=='mailbox').map(account=>account.id),incomeMinor:Number(income.value),startDay:1,mutationKey:crypto.randomUUID()});await refresh();}));}
 root.append(el('h2','Saved views'));for(const view of data.views)root.append(button(view.definition.title,()=>app.openLink({url:'/views/'+view.id})));
 root.append(el('p','Share account access from Ri Chat access or app settings. Choose accounts there, then save the host permission.'));
 if(data.owner){const scopes=el('section');scopes.append(el('h2','Account scopes'),button('Review shared scopes',async()=>{const result=await call('finance_list_scopes');for(const scope of result.scopes)scopes.append(el('p',scope.actorId+' · '+scope.operations.join(', ')),button('Revoke '+scope.actorId,async()=>{await call('finance_revoke_scope',{scopeRef:scope.scopeRef});await refresh();}));if(!result.scopes.length)scopes.append(el('p','No shared account scopes.'));}));root.append(scopes);}
 void app.updateModelContext({content:[{type:'text',text:JSON.stringify({formatVersion:1,revision:++revision,state:{selected:[]}})}]});}
app.onhostcontextchanged=context=>{document.documentElement.dataset.theme=context.theme||'light';};
app.ontoolresult=result=>{data=result.structuredContent;render();};app.connect().then(()=>{document.documentElement.dataset.theme=app.getHostContext()?.theme||'light';}).catch(error=>{document.getElementById('error').textContent=error.message});
`;
  return `<!doctype html><html><head><meta charset="utf-8"><style>body{font:15px system-ui;color:#243329;background:#fafbf8;padding:24px}html[data-theme=dark] body{color:#e8eee8;background:#121713}html[data-theme=dark] section{border-color:#52664d}html[data-theme=dark] input,html[data-theme=dark] button,html[data-theme=dark] textarea{color:#e8eee8;background:#19201b;border-color:#52664d}section{border:1px solid #d8ded8;border-radius:12px;padding:20px;margin:16px 0}label{display:block;margin:10px 0}input,button,textarea{font:inherit;padding:8px;border:1px solid #bac6bc;border-radius:6px;background:white}input{margin-left:8px}button{cursor:pointer;margin:6px}textarea{display:block;width:95%;min-height:100px}#error{color:#8c2828}pre{overflow-wrap:anywhere;white-space:pre-wrap}</style></head><body><p id="error" role="alert"></p><p id="notice" role="status"></p><main id="root">Opening finances</main><script>${(sdk + "\n" + script).replaceAll("</script", "<\\/script")}</script></body></html>`;
}
